package com.group01.asm2.enums;

/**
 * @author Group 01
 */
public enum ActivityActionType {
    LOGIN,
    LOGOUT,

    CREATE_USER,
    READ_USER,
    UPDATE_PROFILE,
    DELETE_USER,

    CREATE_CATEGORY,
    UPDATE_CATEGORY,
    DELETE_CATEGORY,

    CREATE_ITEM,
    UPDATE_ITEM,
    DELETE_ITEM,
    MODERATE_ITEM,

    CREATE_AUCTION,
    UPDATE_AUCTION,
    CANCEL_AUCTION,
    DELETE_AUCTION,
    PROCESS_AUCTION,

    PLACE_BID,

    REQUEST_TOP_UP,
    APPROVE_TOP_UP,
    REJECT_TOP_UP,

    CREATE_PAYMENT,
    UPDATE_PAYMENT_STATUS,

    READ_REPORT,
    EXPORT_REPORT,

    ADD_TO_WATCHLIST,
    REMOVE_FROM_WATCHLIST
}